name: Go Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - created  # Trigger when a new release is created

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Use a specific version of the checkout action

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18  # Update to your desired Go version

      - name: Build
        run: go build -v -o simple-cal -ldflags "-s -w" ./...

      - name: Test
        run: go test -v ./... 

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Release Artifacts
          path: ./simple-cal

  release:
    needs: build  # Ensure that the 'build' job is completed before creating a release
    runs-on: ubuntu-latest
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          draft: false
          prerelease: false
